### PR TITLE
build universal wheels

### PR DESCRIPTION
**Pull request by daa**
It's better to build universal wheels if code supports both Python2 and Python3, so I've changed setup.cfg. Also added Python3.4 and Python3.5 to tox.ini.

### CODE REVIEW

**Comment by estebistec** [comment]
Thanks for the update!

**Comment by estebistec** [comment]
Sure. I can later after work.

**Comment by estebistec** [comment]
Released: https://pypi.python.org/pypi/memoized-property/1.0.3

**Comment by daa** [comment]
Thank you very much.

**Pull request merged**
